import os
import sqlite3
import time
import mimetypes
import shutil
from flask import Flask, render_template, request, jsonify, send_from_directory, abort, session, redirect, url_for
from werkzeug.utils import secure_filename

app = Flask(__name__)

# --- Directories ---
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
app.config["UPLOAD_FOLDER"] = os.path.join(BASE_DIR, "uploads")
app.config["SHARED_FOLDER"] = os.path.join(BASE_DIR, "shared_files")
os.makedirs(app.config["UPLOAD_FOLDER"], exist_ok=True)
os.makedirs(app.config["SHARED_FOLDER"], exist_ok=True)

# --- Limits ---
app.config["MAX_CONTENT_LENGTH"] = 1024 * 1024 * 1024  # 1 GB for file board
CHAT_MAX_CONTENT = 16 * 1024 * 1024  # 16 MB for chat images
ALLOWED_EXTENSIONS = {"png", "jpg", "jpeg", "gif", "webp"}

DB_PATH = os.path.join(BASE_DIR, "chat.db")

# --- Admin & Session ---
app.config["ADMIN_PASSWORD"] = "@Ram19Jam78*6603"
app.secret_key = "popup-chat-secret-key-change-me"

# --- Config override (generated by setup.py) ---
try:
    from config import ADMIN_PASSWORD, SECRET_KEY
    app.config["ADMIN_PASSWORD"] = ADMIN_PASSWORD
    app.secret_key = SECRET_KEY
except ImportError:
    pass  # fall back to defaults during development


# ---------------------------------------------------------------------------
# Database helpers
# ---------------------------------------------------------------------------
def get_db():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


def init_db():
    conn = get_db()
    conn.execute(
        """CREATE TABLE IF NOT EXISTS messages (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            username TEXT NOT NULL,
            message TEXT DEFAULT "",
            image_path TEXT DEFAULT NULL,
            timestamp REAL NOT NULL
        )"""
    )
    conn.execute(
        """CREATE TABLE IF NOT EXISTS shared_files (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            filename TEXT NOT NULL,
            original_name TEXT NOT NULL,
            size INTEGER NOT NULL,
            file_type TEXT DEFAULT "",
            uploaded_at TEXT NOT NULL,
            uploaded_by TEXT DEFAULT "anonymous"
        )"""
    )
    conn.commit()
    conn.close()


def allowed_file(filename):
    return (
        "." in filename
        and filename.rsplit(".", 1)[1].lower() in ALLOWED_EXTENSIONS
    )


def get_storage_used():
    """Return total bytes used by uploads/ and shared_files/."""
    total = 0
    for folder in [app.config["UPLOAD_FOLDER"], app.config["SHARED_FOLDER"]]:
        for dirpath, dirnames, filenames in os.walk(folder):
            for f in filenames:
                fp = os.path.join(dirpath, f)
                try:
                    total += os.path.getsize(fp)
                except OSError:
                    pass
    return total


# ---------------------------------------------------------------------------
# Landing page
# ---------------------------------------------------------------------------
@app.route("/")
def index():
    return render_template("index.html")


# ---------------------------------------------------------------------------
# Chat routes  (unchanged behaviour, now at /chat)
# ---------------------------------------------------------------------------
@app.route("/chat")
def chat_page():
    return render_template("chat.html")


@app.route("/send", methods=["POST"])
def send_message():
    data = request.get_json()
    if not data:
        return jsonify({"error": "Invalid JSON"}), 400
    username = data.get("username", "").strip()
    message = data.get("message", "").strip()
    if not username:
        return jsonify({"error": "Username is required"}), 400
    if not message:
        return jsonify({"error": "Message is required"}), 400
    conn = get_db()
    conn.execute(
        "INSERT INTO messages (username, message, timestamp) VALUES (?, ?, ?)",
        (username, message, time.time()),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "ok"}), 201


@app.route("/upload", methods=["POST"])
def upload_image():
    username = request.form.get("username", "").strip()
    if not username:
        return jsonify({"error": "Username is required"}), 400
    if "image" not in request.files:
        return jsonify({"error": "No image file provided"}), 400
    file = request.files["image"]
    if file.filename == "" or not allowed_file(file.filename):
        return jsonify({"error": "Invalid or missing file"}), 400
    ts = str(int(time.time()))
    filename = secure_filename(ts + "_" + file.filename)
    filepath = os.path.join(app.config["UPLOAD_FOLDER"], filename)
    file.save(filepath)
    message = request.form.get("message", "").strip()
    conn = get_db()
    conn.execute(
        "INSERT INTO messages (username, message, image_path, timestamp) VALUES (?, ?, ?, ?)",
        (username, message, filename, time.time()),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "ok", "filename": filename}), 201


@app.route("/messages")
def get_messages():
    conn = get_db()
    rows = conn.execute(
        "SELECT id, username, message, image_path, timestamp FROM messages ORDER BY id DESC LIMIT 50"
    ).fetchall()
    conn.close()
    messages = []
    for row in reversed(rows):
        msg = {
            "id": row["id"],
            "username": row["username"],
            "message": row["message"],
            "timestamp": row["timestamp"],
        }
        msg["image_url"] = "/uploads/" + row["image_path"] if row["image_path"] else None
        messages.append(msg)
    return jsonify(messages)


@app.route("/uploads/<filename>")
def uploaded_file(filename):
    return send_from_directory(app.config["UPLOAD_FOLDER"], filename)


# ---------------------------------------------------------------------------
# File sharing board
# ---------------------------------------------------------------------------
@app.route("/files")
def files_page():
    return render_template("files.html")


@app.route("/files/api")
def files_api():
    conn = get_db()
    rows = conn.execute(
        "SELECT id, filename, original_name, size, file_type, uploaded_at, uploaded_by "
        "FROM shared_files ORDER BY id DESC"
    ).fetchall()
    conn.close()
    files = []
    for row in rows:
        files.append(
            {
                "id": row["id"],
                "filename": row["filename"],
                "original_name": row["original_name"],
                "size": row["size"],
                "file_type": row["file_type"],
                "uploaded_at": row["uploaded_at"],
                "uploaded_by": row["uploaded_by"],
            }
        )
    return jsonify(files)


@app.route("/upload-file", methods=["POST"])
def upload_file():
    username = request.form.get("username", "anonymous").strip()
    if "file" not in request.files:
        return jsonify({"error": "No file provided"}), 400
    file = request.files["file"]
    if file.filename == "":
        return jsonify({"error": "No file selected"}), 400
    original_name = file.filename
    ts = str(int(time.time()))
    filename = secure_filename(ts + "_" + original_name)
    filepath = os.path.join(app.config["SHARED_FOLDER"], filename)
    file.save(filepath)
    size = os.path.getsize(filepath)
    file_type = mimetypes.guess_type(original_name)[0] or "application/octet-stream"
    conn = get_db()
    conn.execute(
        "INSERT INTO shared_files (filename, original_name, size, file_type, uploaded_at, uploaded_by) "
        "VALUES (?, ?, ?, ?, ?, ?)",
        (filename, original_name, size, file_type, str(time.time()), username),
    )
    conn.commit()
    conn.close()
    return jsonify({"status": "ok", "filename": filename}), 201


@app.route("/download/<filename>")
def download_file(filename):
    safe_name = secure_filename(filename)
    filepath = os.path.join(app.config["SHARED_FOLDER"], safe_name)
    if not os.path.exists(filepath):
        abort(404)
    return send_from_directory(
        app.config["SHARED_FOLDER"],
        safe_name,
        as_attachment=True,
    )


# ---------------------------------------------------------------------------
# Stats
# ---------------------------------------------------------------------------
@app.route("/api/stats")
def api_stats():
    conn = get_db()
    # Active users: distinct usernames with messages in last 5 minutes
    cutoff = time.time() - 300
    user_row = conn.execute(
        "SELECT COUNT(DISTINCT username) AS cnt FROM messages WHERE timestamp >= ?",
        (cutoff,),
    ).fetchone()
    active_users = user_row["cnt"] if user_row else 0

    total_row = conn.execute("SELECT COUNT(*) AS cnt FROM messages").fetchone()
    total_messages = total_row["cnt"] if total_row else 0

    files_row = conn.execute("SELECT COUNT(*) AS cnt FROM shared_files").fetchone()
    total_files = files_row["cnt"] if files_row else 0

    conn.close()
    return jsonify(
        {
            "users": active_users,
            "messages_total": total_messages,
            "files_total": total_files,
        }
    )


# ---------------------------------------------------------------------------
# iOS captive portal detection
# ---------------------------------------------------------------------------
@app.route("/library/test/success.html")
def captive_portal_apple():
    return (
        "<HTML><HEAD><TITLE>Success</TITLE></HEAD><BODY>Success</BODY></HTML>",
        200,
        {"Content-Type": "text/html"},
    )


@app.route("/hotspot-detect.html")
def captive_portal_hotspot():
    return (
        "<HTML><HEAD><TITLE>Success</TITLE></HEAD><BODY>Success</BODY></HTML>",
        200,
        {"Content-Type": "text/html"},
    )


# ---------------------------------------------------------------------------
# Admin Panel Routes
# ---------------------------------------------------------------------------
@app.route("/admin")
def admin_page():
    if session.get("admin"):
        return redirect(url_for("admin_dashboard"))
    return render_template("admin.html")


@app.route("/admin/login", methods=["POST"])
def admin_login():
    data = request.get_json()
    if not data:
        return jsonify({"error": "Invalid JSON"}), 400
    password = data.get("password", "")
    if password == app.config["ADMIN_PASSWORD"]:
        session["admin"] = True
        return jsonify({"status": "ok"}), 200
    return jsonify({"error": "Invalid password"}), 401


@app.route("/admin/dashboard")
def admin_dashboard():
    if not session.get("admin"):
        return redirect(url_for("admin_page"))
    return render_template("admin.html")


@app.route("/admin/api/messages")
def admin_api_messages():
    if not session.get("admin"):
        return jsonify({"error": "Unauthorized"}), 401
    conn = get_db()
    rows = conn.execute(
        "SELECT id, username, message, image_path, timestamp FROM messages ORDER BY id DESC LIMIT 200"
    ).fetchall()
    conn.close()
    messages = []
    for row in rows:
        messages.append(
            {
                "id": row["id"],
                "username": row["username"],
                "message": row["message"],
                "image_path": row["image_path"],
                "timestamp": row["timestamp"],
            }
        )
    return jsonify(messages)


@app.route("/admin/api/files")
def admin_api_files():
    if not session.get("admin"):
        return jsonify({"error": "Unauthorized"}), 401
    conn = get_db()
    rows = conn.execute(
        "SELECT id, filename, original_name, size, file_type, uploaded_at, uploaded_by "
        "FROM shared_files ORDER BY id DESC"
    ).fetchall()
    conn.close()
    files = []
    for row in rows:
        files.append(
            {
                "id": row["id"],
                "filename": row["filename"],
                "original_name": row["original_name"],
                "size": row["size"],
                "file_type": row["file_type"],
                "uploaded_at": row["uploaded_at"],
                "uploaded_by": row["uploaded_by"],
            }
        )
    return jsonify(files)


@app.route("/admin/api/users")
def admin_api_users():
    if not session.get("admin"):
        return jsonify({"error": "Unauthorized"}), 401
    conn = get_db()
    rows = conn.execute(
        "SELECT username, COUNT(*) AS cnt FROM messages GROUP BY username ORDER BY cnt DESC"
    ).fetchall()
    conn.close()
    users = [{"username": row["username"], "count": row["cnt"]} for row in rows]
    return jsonify(users)


@app.route("/admin/api/stats")
def admin_api_stats():
    if not session.get("admin"):
        return jsonify({"error": "Unauthorized"}), 401
    conn = get_db()
    total_msgs = conn.execute("SELECT COUNT(*) AS cnt FROM messages").fetchone()["cnt"]
    total_files = conn.execute("SELECT COUNT(*) AS cnt FROM shared_files").fetchone()["cnt"]
    cutoff = time.time() - 300
    active = conn.execute(
        "SELECT COUNT(DISTINCT username) AS cnt FROM messages WHERE timestamp >= ?",
        (cutoff,),
    ).fetchone()["cnt"]
    conn.close()
    storage = get_storage_used()
    return jsonify(
        {
            "messages_total": total_msgs,
            "files_total": total_files,
            "active_users": active,
            "storage_bytes": storage,
        }
    )


@app.route("/admin/api/clear-chat", methods=["POST"])
def admin_clear_chat():
    if not session.get("admin"):
        return jsonify({"error": "Unauthorized"}), 401
    conn = get_db()
    conn.execute("DELETE FROM messages")
    conn.commit()
    conn.close()
    # Delete all files in uploads/
    upload_dir = app.config["UPLOAD_FOLDER"]
    for f in os.listdir(upload_dir):
        fp = os.path.join(upload_dir, f)
        try:
            if os.path.isfile(fp):
                os.unlink(fp)
        except OSError:
            pass
    return jsonify({"status": "ok"})


@app.route("/admin/api/delete-message/<int:msg_id>", methods=["POST"])
def admin_delete_message(msg_id):
    if not session.get("admin"):
        return jsonify({"error": "Unauthorized"}), 401
    conn = get_db()
    row = conn.execute("SELECT image_path FROM messages WHERE id = ?", (msg_id,)).fetchone()
    if row and row["image_path"]:
        img_path = os.path.join(app.config["UPLOAD_FOLDER"], row["image_path"])
        try:
            if os.path.isfile(img_path):
                os.unlink(img_path)
        except OSError:
            pass
    conn.execute("DELETE FROM messages WHERE id = ?", (msg_id,))
    conn.commit()
    conn.close()
    return jsonify({"status": "ok"})


@app.route("/admin/api/delete-file/<int:file_id>", methods=["POST"])
def admin_delete_file(file_id):
    if not session.get("admin"):
        return jsonify({"error": "Unauthorized"}), 401
    conn = get_db()
    row = conn.execute("SELECT filename FROM shared_files WHERE id = ?", (file_id,)).fetchone()
    if row:
        file_path = os.path.join(app.config["SHARED_FOLDER"], row["filename"])
        try:
            if os.path.isfile(file_path):
                os.unlink(file_path)
        except OSError:
            pass
        conn.execute("DELETE FROM shared_files WHERE id = ?", (file_id,))
        conn.commit()
    conn.close()
    return jsonify({"status": "ok"})


@app.route("/admin/api/kick-user", methods=["POST"])
def admin_kick_user():
    if not session.get("admin"):
        return jsonify({"error": "Unauthorized"}), 401
    data = request.get_json()
    if not data or not data.get("username"):
        return jsonify({"error": "Username required"}), 400
    username = data["username"].strip()
    conn = get_db()
    # Get messages with images to also delete those files
    rows = conn.execute(
        "SELECT image_path FROM messages WHERE username = ? AND image_path IS NOT NULL",
        (username,),
    ).fetchall()
    for row in rows:
        img_path = os.path.join(app.config["UPLOAD_FOLDER"], row["image_path"])
        try:
            if os.path.isfile(img_path):
                os.unlink(img_path)
        except OSError:
            pass
    conn.execute("DELETE FROM messages WHERE username = ?", (username,))
    conn.commit()
    deleted = conn.execute("SELECT changes()").fetchone()[0]
    conn.close()
    return jsonify({"status": "ok", "messages_deleted": deleted})


@app.route("/admin/logout")
def admin_logout():
    session.pop("admin", None)
    return redirect(url_for("admin_page"))


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Catch-all captive portal handler
# ---------------------------------------------------------------------------
@app.route("/generate_204")
@app.route("/connecttest.txt")
def captive_portal_android():
    return redirect(url_for("index"))

@app.errorhandler(404)
def catch_all(e):
    return redirect(url_for("index"))

if __name__ == "__main__":
    init_db()
    app.run(host="0.0.0.0", port=5000, debug=True)

# ---------------------------------------------------------------------------
# Catch-all captive portal handler
# ---------------------------------------------------------------------------
@app.route("/generate_204")
@app.route("/connecttest.txt")
def captive_portal_android():
    return redirect(url_for("index"))

@app.errorhandler(404)
def catch_all(e):
    return redirect(url_for("index"))

# ---------------------------------------------------------------------------
# Catch-all captive portal handler
# ---------------------------------------------------------------------------
@app.route("/generate_204")
@app.route("/connecttest.txt")
def captive_portal_android():
    return redirect(url_for("index"))

@app.errorhandler(404)
def catch_all(e):
    return redirect(url_for("index"))
