#!/bin/bash
# ╔══════════════════════════════════════════════════════════════╗
# ║   Pirate Chat — All-in-One Installer                       ║
# ║   Installs: app + hotspot + captive portal + systemd        ║
# ╚══════════════════════════════════════════════════════════════╝
#
# Run this on a FRESH Raspberry Pi OS (Bookworm+) to set up
# Pirate Chat as a standalone WiFi hotspot with captive portal.
#
# Usage:
#   sudo bash install-piratechat.sh
#
# You will be prompted for the admin password and WiFi SSID during
# setup. To skip prompts (for automation), pass args:
#   sudo bash install-piratechat.sh --password YourPass --ssid MyNet
#
# Must have internet access on first run (for apt/pip packages).
# After completion, the Pi becomes its own access point -- connect
# any device to the SSID and Pirate Chat opens automatically.

set -euo pipefail

# Config
# Detect the real user (even when running via sudo)
REAL_USER=${SUDO_USER:-$(whoami)}
REAL_HOME=$(eval echo "~$REAL_USER")
APP_DIR="$REAL_HOME/pirate-chat"
REPO_URL="https://github.com/ameggs/pirate-chat.git"
APP_PORT="5000"
HOTSPOT_IP="10.42.0.1"

# Parse CLI args
CLI_PASSWORD=""
CLI_SSID=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --password) CLI_PASSWORD="$2"; shift 2 ;;
        --ssid)     CLI_SSID="$2"; shift 2 ;;
        *)          echo "Unknown: $1"; exit 1 ;;
    esac
done

# Banner
echo ""
echo "  +----------------------------------------------+"
echo "  |     Pirate Chat -- All-in-One Installer       |"
echo "  +----------------------------------------------+"
echo ""

# Interactive prompts (only if CLI args not given)
if [[ -z "$CLI_SSID" ]]; then
    read -r -p "  WiFi network name (SSID) [piratechat]: " input_ssid
    SSID="${input_ssid:-piratechat}"
else
    SSID="$CLI_SSID"
fi

if [[ -z "$CLI_PASSWORD" ]]; then
    echo "  Set an admin password for the dashboard."
    while true; do
        read -r -s -p "  Admin password: " pw1
        echo ""
        if [[ -z "$pw1" ]]; then
            echo "  Password cannot be empty"
            continue
        fi
        read -r -s -p "  Confirm password: " pw2
        echo ""
        if [[ "$pw1" != "$pw2" ]]; then
            echo "  Passwords do not match"
            continue
        fi
        break
    done
    ADMIN_PASSWORD="$pw1"
else
    ADMIN_PASSWORD="$CLI_PASSWORD"
fi

# Generate a random secret key
SECRET_KEY="$(tr -dc 'a-f0-9' < /dev/urandom | head -c 64 2>/dev/null || echo dummy)"

echo ""
echo "  SSID:       $SSID"
echo "  App dir:    $APP_DIR"
echo ""

# Step 1: System dependencies
echo "  Step 1: Installing system packages"
apt update -qq
apt install -y -qq python3 python3-pip git network-manager iptables dnsmasq-base 2>&1 | tail -1
echo "  OK - System packages installed"

# Step 2: Clone app
echo "  Step 2: Cloning Pirate Chat"
if [[ -d "$APP_DIR" ]]; then
    echo "  Directory exists -- updating..."
    cd "$APP_DIR"
    git pull 2>&1 | tail -1
else
    git clone "$REPO_URL" "$APP_DIR" 2>&1 | tail -1
fi
cd "$APP_DIR"
echo "  OK - App cloned"

# Step 3: Install Python dependencies
echo "  Step 3: Installing Python packages"
pip3 install --break-system-packages -r requirements.txt 2>&1 | tail -1
echo "  OK - Python packages installed"

# Step 4: Create data directories and config
echo "  Step 4: Creating data directories and config"
mkdir -p "$APP_DIR/uploads" "$APP_DIR/shared_files"
chown -R "$REAL_USER:$REAL_USER" "$APP_DIR/uploads" "$APP_DIR/shared_files"

cat > "$APP_DIR/config.py" << CONFIGEOF
# Pirate Chat Configuration
# Auto-generated by installer -- DO NOT COMMIT TO GIT

ADMIN_PASSWORD="$ADMIN_PASSWORD"
SECRET_KEY="$SECRET_KEY"
CONFIGEOF

chown "$REAL_USER:$REAL_USER" "$APP_DIR/config.py"
chmod 600 "$APP_DIR/config.py"
echo "  OK - Config written"

# Step 5: Systemd service
echo "  Step 5: Installing systemd service"
cat > /etc/systemd/system/pirate-chat.service << SERVICEEOF
[Unit]
Description=Pirate Chat App with Image Upload
After=network.target

[Service]
Type=simple
User=$REAL_USER
WorkingDirectory=$APP_DIR
ExecStart=/usr/bin/python3 $APP_DIR/app.py
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
SERVICEEOF

systemctl daemon-reload
systemctl enable pirate-chat
systemctl restart pirate-chat
echo "  OK - systemd service installed and started"

# Step 6: Hotspot + Captive Portal
echo "  Step 6: Configuring WiFi hotspot and captive portal"

WIFI_IFACE=""
for iface in /sys/class/net/*; do
    name=$(basename "$iface")
    if iw dev "$name" info 2>/dev/null 1>/dev/null; then
        WIFI_IFACE="$name"
        break
    fi
done

if [[ -z "$WIFI_IFACE" ]]; then
    echo "  No WiFi interface found -- hotspot skipped"
else
    echo "  Using interface: $WIFI_IFACE"

    # Delete any existing profile with this name
    nmcli connection delete "$SSID" 2>/dev/null || true

    # Create hotspot connection
    nmcli connection add \
        type wifi \
        ifname "$WIFI_IFACE" \
        con-name "$SSID" \
        ssid "$SSID" \
        802-11-wireless.mode ap \
        802-11-wireless.band bg \
        ipv4.method shared

    nmcli connection modify "$SSID" connection.autoconnect-priority 100

    # DNS catch-all for captive portal
    mkdir -p /etc/NetworkManager/dnsmasq-shared.d/
    cat > /etc/NetworkManager/dnsmasq-shared.d/pirate-chat-portal.conf << DNSEOF
address=/#/$HOTSPOT_IP
DNSEOF
    echo "  OK - DNS catch-all configured"

    # Port redirect script
    cat > /usr/local/bin/pirate-chat-redirect.sh << 'REDIRECTEOF'
#!/bin/bash
iptables -t nat -C PREROUTING -i wlan0 -p tcp --dport 80 -j REDIRECT --to-port 5000 2>/dev/null || \
    iptables -t nat -A PREROUTING -i wlan0 -p tcp --dport 80 -j REDIRECT --to-port 5000
iptables -t nat -C PREROUTING -i wlan0 -p tcp --dport 443 -j REDIRECT --to-port 5000 2>/dev/null || \
    iptables -t nat -A PREROUTING -i wlan0 -p tcp --dport 443 -j REDIRECT --to-port 5000
REDIRECTEOF
    chmod +x /usr/local/bin/pirate-chat-redirect.sh

    # NetworkManager dispatcher
    cat > /etc/NetworkManager/dispatcher.d/99-pirate-chat << 'DISPATCHEOF'
#!/bin/bash
if [ "$1" = "wlan0" ] && [ "$2" = "up" ]; then
    /usr/local/bin/pirate-chat-redirect.sh
fi
DISPATCHEOF
    chmod +x /etc/NetworkManager/dispatcher.d/99-pirate-chat

    # Apply rules now
    /usr/local/bin/pirate-chat-redirect.sh

    # Bring up the hotspot
    nmcli connection up "$SSID" 2>&1 || true
    echo "  OK - Hotspot configured -- captive portal active"
fi

# Summary
echo ""
echo "  +----------------------------------------------+"
echo "  |     Pirate Chat is ready to sail!             |"
echo "  +----------------------------------------------+"
echo ""
echo "  WiFi hotspot:   $SSID (no password)"
echo "  App URL:        http://$HOTSPOT_IP:$APP_PORT"
echo "  Admin panel:    http://$HOTSPOT_IP:$APP_PORT/admin"
echo ""
echo "  Service: sudo systemctl status pirate-chat"
echo "  Logs:    sudo journalctl -u pirate-chat -f"
echo ""
