#!/bin/bash
# ╔══════════════════════════════════════════════════════════════╗
# ║   Pirate Chat — All-in-One Installer                       ║
# ║   Installs: app + hotspot + captive portal + systemd        ║
# ╚══════════════════════════════════════════════════════════════╝
#
# Run this on a FRESH Raspberry Pi OS (Bookworm+) to set up
# Pirate Chat as a standalone WiFi hotspot with captive portal.
#
# Usage:
#   sudo bash install-piratechat.sh [--password PASSWORD] [--ssid SSID]
#
#   --password   Admin panel password (auto-generated if omitted)
#   --ssid       WiFi hotspot SSID (default: piratechat)
#
# Must have internet access on first run (for apt/pip packages).
# After completion, the Pi becomes its own access point — connect
# any device to the SSID and Pirate Chat opens automatically.

set -euo pipefail

# ─── Config ────────────────────────────────────────────────────
APP_DIR="/home/pi/pirate-chat"
REPO_URL="https://github.com/ameggs/pirate-chat.git"
APP_PORT="5000"
HOTSPOT_IP="10.42.0.1"

# Parse args
ADMIN_PASSWORD=""
SSID="piratechat"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --password) ADMIN_PASSWORD="$2"; shift 2 ;;
        --ssid)     SSID="$2"; shift 2 ;;
        *)          echo "Unknown: $1"; exit 1 ;;
    esac
done

# Auto-generate password if not provided
if [[ -z "$ADMIN_PASSWORD" ]]; then
    ADMIN_PASSWORD=$(tr -dc 'A-Za-z0-9!@#$%^&*()_+' < /dev/urandom | head -c 20 2>/dev/null || echo "pirate$(date +%s)")
fi

SECRET_KEY=$(tr -dc 'a-f0-9' < /dev/urandom | head -c 64 2>/dev/null || echo "$(date +%s)$(hostname)" | md5sum | head -c 64)

# ─── Banner ────────────────────────────────────────────────────
echo ""
echo "  ╔══════════════════════════════════════════════╗"
echo "  ║     Pirate Chat — All-in-One Installer        ║"
echo "  ╚══════════════════════════════════════════════╝"
echo ""
echo "  SSID:       $SSID"
echo "  Admin pass: $ADMIN_PASSWORD"
echo "  App dir:    $APP_DIR"
echo ""

# ─── 1. System dependencies ────────────────────────────────────
echo "  ─── (1/6) Installing system packages ───"
apt update -qq
apt install -y -qq python3 python3-pip git network-manager iptables dnsmasq-base 2>&1 | tail -1
echo "  ✅  System packages installed"

# ─── 2. Clone app ──────────────────────────────────────────────
echo "  ─── (2/6) Cloning Pirate Chat ───"
if [[ -d "$APP_DIR" ]]; then
    echo "  ℹ️   Directory exists — updating..."
    cd "$APP_DIR"
    git pull 2>&1 | tail -1
else
    git clone "$REPO_URL" "$APP_DIR" 2>&1 | tail -1
fi
cd "$APP_DIR"
echo "  ✅  App cloned"

# ─── 3. Install Python dependencies ────────────────────────────
echo "  ─── (3/6) Installing Python packages ───"
pip3 install --break-system-packages -r requirements.txt 2>&1 | tail -1
echo "  ✅  Python packages installed"

# ─── 4. Create data directories & config ───────────────────────
echo "  ─── (4/6) Creating data directories & config ───"
mkdir -p "$APP_DIR/uploads" "$APP_DIR/shared_files"
chown -R pi:pi "$APP_DIR/uploads" "$APP_DIR/shared_files"

cat > "$APP_DIR/config.py" << CONFIGEOF
# Pirate Chat Configuration
# Auto-generated by installer — DO NOT COMMIT TO GIT

ADMIN_PASSWORD="$ADMIN_PASSWORD"
SECRET_KEY="$SECRET_KEY"
CONFIGEOF

chown pi:pi "$APP_DIR/config.py"
chmod 600 "$APP_DIR/config.py"
echo "  ✅  Config written"

# ─── 5. Systemd service ────────────────────────────────────────
echo "  ─── (5/6) Installing systemd service ───"
cat > /etc/systemd/system/pirate-chat.service << SERVICEEOF
[Unit]
Description=Pirate Chat App with Image Upload
After=network.target

[Service]
Type=simple
User=pi
WorkingDirectory=$APP_DIR
ExecStart=/usr/bin/python3 $APP_DIR/app.py
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
SERVICEEOF

systemctl daemon-reload
systemctl enable pirate-chat
systemctl restart pirate-chat
echo "  ✅  systemd service installed and started"

# ─── 6. Hotspot + Captive Portal ───────────────────────────────
echo "  ─── (6/6) Configuring WiFi hotspot & captive portal ───"

WIFI_IFACE=""
for iface in /sys/class/net/*; do
    name=$(basename "$iface")
    if iw dev "$name" info &>/dev/null 2>&1; then
        WIFI_IFACE="$name"
        break
    fi
done

if [[ -z "$WIFI_IFACE" ]]; then
    echo "  ⚠️   No WiFi interface found — hotspot skipped"
else
    echo "  📡  Using interface: $WIFI_IFACE"

    # Delete any existing profile with this name
    nmcli connection delete "$SSID" 2>/dev/null || true

    # Create hotspot connection
    nmcli connection add \
        type wifi \
        ifname "$WIFI_IFACE" \
        con-name "$SSID" \
        ssid "$SSID" \
        802-11-wireless.mode ap \
        802-11-wireless.band bg \
        ipv4.method shared

    nmcli connection modify "$SSID" connection.autoconnect-priority 100

    # DNS catch-all for captive portal
    mkdir -p /etc/NetworkManager/dnsmasq-shared.d/
    cat > /etc/NetworkManager/dnsmasq-shared.d/pirate-chat-portal.conf << DNSEOF
address=/#/$HOTSPOT_IP
DNSEOF
    echo "  ✅  DNS catch-all configured"

    # Port redirect script (80/443 -> 5000)
    cat > /usr/local/bin/pirate-chat-redirect.sh << 'REDIRECTEOF'
#!/bin/bash
iptables -t nat -C PREROUTING -i wlan0 -p tcp --dport 80 -j REDIRECT --to-port 5000 2>/dev/null || \
    iptables -t nat -A PREROUTING -i wlan0 -p tcp --dport 80 -j REDIRECT --to-port 5000
iptables -t nat -C PREROUTING -i wlan0 -p tcp --dport 443 -j REDIRECT --to-port 5000 2>/dev/null || \
    iptables -t nat -A PREROUTING -i wlan0 -p tcp --dport 443 -j REDIRECT --to-port 5000
REDIRECTEOF
    chmod +x /usr/local/bin/pirate-chat-redirect.sh

    # NetworkManager dispatcher — re-apply rules on hotspot start
    cat > /etc/NetworkManager/dispatcher.d/99-pirate-chat << 'DISPATCHEOF'
#!/bin/bash
if [ "$1" = "wlan0" ] && [ "$2" = "up" ]; then
    /usr/local/bin/pirate-chat-redirect.sh
fi
DISPATCHEOF
    chmod +x /etc/NetworkManager/dispatcher.d/99-pirate-chat

    # Apply rules now
    /usr/local/bin/pirate-chat-redirect.sh

    # Bring up the hotspot (disconnects any WiFi client)
    nmcli connection up "$SSID" 2>&1 || true
    echo "  ✅  Hotspot '$SSID' configured — captive portal active"
fi

# ─── Summary ───────────────────────────────────────────────────
echo ""
echo "  ╔══════════════════════════════════════════════╗"
echo "  ║     Pirate Chat is ready to sail! 🏴‍☠️       ║"
echo "  ╚══════════════════════════════════════════════╝"
echo ""
echo "  📡  WiFi hotspot:   $SSID (no password)"
echo "  🌐  App URL:        http://$HOTSPOT_IP:$APP_PORT"
echo "  🔐  Admin panel:    http://$HOTSPOT_IP:$APP_PORT/admin"
echo "  🔑  Admin password: $ADMIN_PASSWORD"
echo ""
echo "  📋  Service: sudo systemctl status pirate-chat"
echo "  📋  Logs:    sudo journalctl -u pirate-chat -f"
echo ""
