#!/usr/bin/env python3
"""
Pirate Chat — Setup & Installer
===============================
Run this once to configure Pirate Chat on your system.
Prompts for admin password and generates a secure secret key.
"""

import os
import sys
import secrets
import shutil
import subprocess

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# ---------------------------------------------------------------------------
# Utilities
# ---------------------------------------------------------------------------

def ask(prompt, default=None, secret=False):
    """Ask the user for input with an optional default value."""
    if default:
        prompt = f"{prompt} [{default}]: "
    else:
        prompt = f"{prompt}: "

    import getpass
    if secret:
        value = getpass.getpass(prompt)
    else:
        value = input(prompt).strip()

    if not value and default:
        return default
    return value


def write_config(password, secret_key):
    """Write config.py with user-supplied values."""
    path = os.path.join(BASE_DIR, "config.py")
    content = f"""# Pirate Chat Configuration
# Auto-generated by setup.py — DO NOT COMMIT TO GIT

ADMIN_PASSWORD="{password}"
SECRET_KEY="{secret_key}"
"""
    with open(path, "w") as f:
        f.write(content)
    print(f"  ✅  config.py written")


def install_dependencies():
    """Install Python packages from requirements.txt."""
    req_path = os.path.join(BASE_DIR, "requirements.txt")
    if not os.path.exists(req_path):
        print("  ⚠️  No requirements.txt found, skipping dependency install")
        return

    print("  📦  Installing dependencies...")
    result = subprocess.run(
        [sys.executable, "-m", "pip", "install", "-r", req_path],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        print(f"  ❌  pip install failed:\n{result.stderr}")
        sys.exit(1)
    print("  ✅  Dependencies installed")


def create_dirs():
    """Ensure data directories exist."""
    for d in ["uploads", "shared_files"]:
        path = os.path.join(BASE_DIR, d)
        os.makedirs(path, exist_ok=True)
        print(f"  ✅  {d}/ directory ready")


def setup_systemd():
    """Optionally install the systemd service."""
    print()
    answer = ask("Install as systemd service (auto-start on boot)?", default="yes")
    if answer.lower() not in ("y", "yes"):
        print("  ⏭️  Skipping systemd setup")
        return

    service_path = os.path.join(BASE_DIR, "pirate-chat.service")
    if not os.path.exists(service_path):
        print("  ⚠️  pirate-chat.service not found in project directory")
        print("  💡  Copy it manually to /etc/systemd/system/")
        return

    # Fix user if running on a Pi (default file has 'andy')
    import pwd
    current_user = pwd.getpwuid(os.getuid()).pw_name
    with open(service_path) as f:
        svc = f.read()
    svc = svc.replace("User=andy", f"User={current_user}")
    svc = svc.replace("/home/andy/", f"/home/{current_user}/")
    tmp_path = "/tmp/pirate-chat.service"
    with open(tmp_path, "w") as f:
        f.write(svc)

    dest = "/etc/systemd/system/pirate-chat.service"
    result = subprocess.run(
        ["sudo", "cp", tmp_path, dest],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        print(f"  ❌  Failed to copy service file:\n{result.stderr}")
        return

    subprocess.run(["sudo", "systemctl", "daemon-reload"], capture_output=True)
    subprocess.run(["sudo", "systemctl", "enable", "pirate-chat"], capture_output=True)
    subprocess.run(["sudo", "systemctl", "start", "pirate-chat"], capture_output=True)
    os.remove(tmp_path)
    print("  ✅  systemd service installed and started")


def setup_hotspot():
    """Optionally configure the WiFi hotspot + captive portal."""
    print()
    answer = ask(
        "Set up WiFi hotspot (standalone mode, no internet needed)?",
        default="yes"
    )
    if answer.lower() not in ("y", "yes"):
        print("  ⏭️  Skipping hotspot setup")
        return

    # Check if running on a Pi with WiFi
    wifi_iface = subprocess.run(
        ["iw", "dev"], capture_output=True, text=True
    ).stdout
    if "wlan" not in wifi_iface:
        print("  ⚠️  No wireless interface found — hotspot requires WiFi")
        print("  💡  You can set it up later with: sudo pirate-chat-hotspot.sh")
        return

    ssid = ask("WiFi network name (SSID)", default="piratechat")
    print(f"  📡  Setting up hotspot '{ssid}'...")

    hotspot_script = os.path.join(BASE_DIR, "pirate-chat-hotspot.sh")
    if os.path.exists(hotspot_script):
        result = subprocess.run(
            ["sudo", "bash", hotspot_script, ssid],
            capture_output=True, text=True,
        )
        print(result.stdout)
        if result.returncode != 0:
            print(f"  ❌  Hotspot setup failed:\n{result.stderr}")
            return
        print("  ✅  WiFi hotspot configured and active!")
        print(f"  🔗  Connect to '{ssid}' and open http://10.42.0.1:5000")
    else:
        print("  ⚠️  pirate-chat-hotspot.sh not found — skipping")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    print()
    print("  ╔══════════════════════════════╗")
    print("  ║   Pirate Chat — Setup Wizard  ║")
    print("  ╚══════════════════════════════╝")
    print()
    print("  Let's get your Pirate Chat server configured.")
    print()

    # ---- Admin password ----
    print("  ─── Admin Panel Password ───")
    print("  This locks the admin dashboard (chat moderation, file management).")
    password1 = ask("  Enter admin password", secret=True)
    if not password1:
        print("  ❌  Password cannot be empty")
        sys.exit(1)
    password2 = ask("  Confirm admin password", secret=True)
    if password1 != password2:
        print("  ❌  Passwords do not match")
        sys.exit(1)
    print("  ✅  Password set")
    print()

    # ---- Secret key ----
    print("  ─── Flask Secret Key ───")
    print("  Used for session security. Auto-generated below.")
    secret_key = secrets.token_hex(32)
    print(f"  🔑  Generated: {secret_key}")
    custom = ask("  Use a custom key instead?", default="no")
    if custom.lower() in ("y", "yes"):
        secret_key = ask("  Enter secret key (min 16 chars)")
        if len(secret_key) < 16:
            print("  ❌  Secret key too short, using auto-generated")
            secret_key = secrets.token_hex(32)
    print()

    # ---- Write config ----
    print("  ─── Writing Configuration ───")
    write_config(password1, secret_key)
    print()

    # ---- Create dirs ----
    print("  ─── Creating Data Directories ───")
    create_dirs()
    print()

    # ---- Install deps ----
    print("  ─── Installing Dependencies ───")
    install_dependencies()
    print()

    # ---- Systemd ----
    print("  ─── Systemd Service (optional) ───")
    setup_systemd()
    print()

    # ---- Hotspot ----
    print("  ─── WiFi Hotspot (optional, Pi only) ───")
    setup_hotspot()
    print()

    # ---- Done ----
    print()
    print("  ╔══════════════════════════════════════════════╗")
    print("  ║    Pirate Chat is ready to sail! 🏴‍☠️        ║")
    print("  ╚══════════════════════════════════════════════╝")
    print()
    print("  To run the app:")
    print(f"    python3 {os.path.join(BASE_DIR, 'app.py')}")
    print()
    print("  Or via systemd (if installed):")
    print("    sudo systemctl status pirate-chat")
    print()
    print("  If hotspot mode was enabled:")
    print("    📡  Connect to the WiFi network and open a browser")
    print("    🌐  The app loads automatically (captive portal)")


if __name__ == "__main__":
    main()
