#!/usr/bin/env python3
"""
Pirate Chat — Setup & Installer
===============================
Run this once to configure Pirate Chat on your system.
Prompts for admin password and generates a secure secret key.
"""

import os
import sys
import secrets
import shutil
import subprocess

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# ---------------------------------------------------------------------------
# Utilities
# ---------------------------------------------------------------------------

def ask(prompt, default=None, secret=False):
    """Ask the user for input with an optional default value."""
    if default:
        prompt = f"{prompt} [{default}]: "
    else:
        prompt = f"{prompt}: "

    import getpass
    if secret:
        value = getpass.getpass(prompt)
    else:
        value = input(prompt).strip()

    if not value and default:
        return default
    return value


def write_config(password, secret_key):
    """Write config.py with user-supplied values."""
    path = os.path.join(BASE_DIR, "config.py")
    content = f"""# Pirate Chat Configuration
# Auto-generated by setup.py — DO NOT COMMIT TO GIT

ADMIN_PASSWORD = "{password}"
SECRET_KEY = "{secret_key}"
"""
    with open(path, "w") as f:
        f.write(content)
    print(f"  ✅  config.py written")


def install_dependencies():
    """Install Python packages from requirements.txt."""
    req_path = os.path.join(BASE_DIR, "requirements.txt")
    if not os.path.exists(req_path):
        print("  ⚠️  No requirements.txt found, skipping dependency install")
        return

    print("  📦  Installing dependencies...")
    result = subprocess.run(
        [sys.executable, "-m", "pip", "install", "-r", req_path],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        print(f"  ❌  pip install failed:\n{result.stderr}")
        sys.exit(1)
    print("  ✅  Dependencies installed")


def create_dirs():
    """Ensure data directories exist."""
    for d in ["uploads", "shared_files"]:
        path = os.path.join(BASE_DIR, d)
        os.makedirs(path, exist_ok=True)
        print(f"  ✅  {d}/ directory ready")


def setup_systemd():
    """Optionally install the systemd service."""
    print()
    answer = ask("Install as systemd service (auto-start on boot)?", default="yes")
    if answer.lower() not in ("y", "yes"):
        print("  ⏭️  Skipping systemd setup")
        return

    service_path = os.path.join(BASE_DIR, "pirate-chat.service")
    if not os.path.exists(service_path):
        print("  ⚠️  pirate-chat.service not found in project directory")
        print("  💡  Copy it manually to /etc/systemd/system/")
        return

    dest = "/etc/systemd/system/pirate-chat.service"
    result = subprocess.run(
        ["sudo", "cp", service_path, dest],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        print(f"  ❌  Failed to copy service file:\n{result.stderr}")
        return

    subprocess.run(["sudo", "systemctl", "daemon-reload"], capture_output=True)
    subprocess.run(["sudo", "systemctl", "enable", "pirate-chat"], capture_output=True)
    subprocess.run(["sudo", "systemctl", "start", "pirate-chat"], capture_output=True)
    print("  ✅  systemd service installed and started")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    print()
    print("  ╔══════════════════════════════╗")
    print("  ║   Pirate Chat — Setup Wizard  ║")
    print("  ╚══════════════════════════════╝")
    print()
    print("  Let's get your Pirate Chat server configured.")
    print()

    # ---- Admin password ----
    print("  ─── Admin Panel Password ───")
    print("  This locks the admin dashboard (chat moderation, file management).")
    password1 = ask("  Enter admin password", secret=True)
    if not password1:
        print("  ❌  Password cannot be empty")
        sys.exit(1)
    password2 = ask("  Confirm admin password", secret=True)
    if password1 != password2:
        print("  ❌  Passwords do not match")
        sys.exit(1)
    print("  ✅  Password set")
    print()

    # ---- Secret key ----
    print("  ─── Flask Secret Key ───")
    print("  Used for session security. Auto-generated below.")
    secret_key = secrets.token_hex(32)
    print(f"  🔑  Generated: {secret_key}")
    custom = ask("  Use a custom key instead?", default="no")
    if custom.lower() in ("y", "yes"):
        secret_key = ask("  Enter secret key (min 16 chars)")
        if len(secret_key) < 16:
            print("  ❌  Secret key too short, using auto-generated")
            secret_key = secrets.token_hex(32)
    print()

    # ---- Write config ----
    print("  ─── Writing Configuration ───")
    write_config(password1, secret_key)
    print()

    # ---- Create dirs ----
    print("  ─── Creating Data Directories ───")
    create_dirs()
    print()

    # ---- Install deps ----
    print("  ─── Installing Dependencies ───")
    install_dependencies()
    print()

    # ---- Systemd ----
    print("  ─── Systemd Service (optional) ───")
    setup_systemd()
    print()

    # ---- Done ----
    print()
    print("  ╔════════════════════════════════════════╗")
    print("  ║    Pirate Chat is ready to sail! 🏴‍☠️    ║")
    print("  ╚════════════════════════════════════════╝")
    print()
    print("  Run it with:")
    print(f"    python3 {os.path.join(BASE_DIR, 'app.py')}")
    print()
    print("  Or if you installed the systemd service:")
    print("    sudo systemctl status pirate-chat")
    print()
    print("  Open http://<your-pi-ip>:5000 in a browser")


if __name__ == "__main__":
    main()
